name: legal_scanner
description: LawBuddy - AI-powered real estate legal document scanner & assistant.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  http: ^1.1.0
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.13.1
  google_fonts: ^6.1.0
  flutter_markdown: ^0.7.3
  shared_preferences: ^2.2.2
  pinput: ^6.0.2
  file_picker: ^11.0.2
  syncfusion_flutter_pdf: ^33.2.13
  syncfusion_flutter_pdfviewer: ^33.2.13
  url_launcher: ^6.3.0
  path_provider: ^2.1.6
  open_filex: ^4.7.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
